language: java
jdk:
  - openjdk8

sudo: required

services:
  - docker

cache:
  directories:
    - ./ui/node_modules
    - $HOME/.npm
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  - TEST_SUITE=ui
  - TEST_SUITE=api

before_install:
  - sudo service mysql stop

install:
  - |
    if [ "${TEST_SUITE}" == "ui" ]; then
      cd ./ui && npm install && cd ..
    fi
  - |
    if [ "${TEST_SUITE}" == "api" ]; then
      ./gradlew assemble
    fi
script:
  - |
    if [ "${TEST_SUITE}" == "ui" ]; then
      cd ./ui && npm run lint && npm run sass-lint && npm run unit && cd ..
    fi
  - |
    if [ "${TEST_SUITE}" == "api" ]; then
      SPRING_PROFILES_ACTIVE=docker ./gradlew check dockerApiTest
    fi
